version: '2'

services:
 web:
  image: nginx:latest
  ports:
    - "1111:80"
    - "1112:443"
  volumes:
    - ./public:/public
    - ./conf/nginx.conf:/etc/nginx/nginx.conf
  links:
   - db
   - php

 php:
  image: php:7-fpm
  volumes:
    - ./public:/public

 db:
  image: mysql:5.7
  ports:
   - "8889:3306"
  volumes:
   - ./db:/var/lib/mysql
  environment:
   - MYSQL_ROOT_PASSWORD=docker
   - MYSQL_DATABASE=lempdave